name: Finish Coveralls build
on:
  push:
    branches:
      - main
      - trunk
      - "release/**"
      - "hotfix/[0-9]+.[0-9]+*"
      - "feature/**"
  pull_request:

# Don't run a second workflow for the same PR or commit if one is already running.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  finish_coveralls_build:
    name: "Finish coveralls build"
    runs-on: ubuntu-latest
    steps:

      # Wait for the PHP and JS tests to finish.
      # NOTE: The ref value should be different when triggered by pull_request event.
      #       See: https://github.com/lewagon/wait-on-check-action/issues/25.
      - name: "Wait on tests (PR)"
        uses: lewagon/wait-on-check-action@e106e5c43e8ca1edea6383a39a01c5ca495fd812 # lewagon/wait-on-check-action@v1.3.1
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: Test|TestJS

      - name: "Wait on tests (push)"
        if: github.event_name != 'pull_request'
        uses: lewagon/wait-on-check-action@e106e5c43e8ca1edea6383a39a01c5ca495fd812 # lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: Test|TestJS


      - name: "Coveralls Finished"
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }} # Connect all builds together.
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          carryforward: "unit-php-7.2,unit-php-8.3,php-7.2-wp-6.2,php-7.2-wp-6.2-ms,php-8.3-wp-trunk,php-8.3-wp-trunk-ms,package-analysis-report,package-browserslist-config,package-components,package-feature-flag,package-helpers,package-js,package-replacement-variable-editor,package-search-metadata-previews,package-social-metadata-forms,package-social-metadata-previews,package-yoast-components"
          parallel-finished: true
